### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KaspianDev** [fuzzbuck/Casanova#6]
What makes you target polish people with malware?

**Comment by KaspianDev** [comment]
I don't know if you know this, but it's not a social media for kids, or to joke, if you want mommy jokes go on facebook.

**Comment by fuzzbuck** [comment]
I don't know if you know this, but this isn't social media for kids, if you want based political agenda go on reddit.

[https://github.com/RIAEvangelist/node-ipc/pull/572]
I don't hate polish people, the PR is a joke and I can't understand your thought process of posting a 'warning about an apparently polo-phobic author' on my project developed to help the Ukrainian & Polish population?
